api/.env.example, api/index.js, api/package.json, api/src/app.js, api/src/db.js, api/src/models/Basket.js, api/src/models/Detail.js, api/src/models/Diet.js, api/src/models/Food.js, api/src/models/Review.js, api/src/models/User.js, api/src/routes/indexRouter.js, comments.txt
=> Added basic api structure

comments.txt
=> Updated comments on comments.txt

api/src/models/Diet.js, api/src/models/Food.js
=> actualizando modelos de food y diet

api/src/controllers/dietsControllers.js, api/src/controllers/foodControllers.js, api/src/handlers/dietHandlers.js, api/src/handlers/foodHandlers.js, api/src/routes/dietsRouter.js, api/src/routes/foodRouter.js, api/src/routes/indexRouter.js, client/src/components/Nav/Nav.jsx
Creo estructura de las rutas, handlers y controllers
=> Structure routes

client/package.json, client/src/components/DashBoard/DashBoard.jsx
=> modelando el dashboard

client/hardcodedFoods.js, client/src/App.jsx, client/src/main.jsx, client/src/redux/configGuide.txt, client/src/redux/foodActions.js, client/src/redux/foodSlice.js, client/src/redux/store.js, client/src/views/ReduxExperiment.jsx
=> Redux initial config

api/.env.example, api/api.js, api/index.js, api/src/app.js, api/src/controllers/foodControllers/deleteFoodControllers.js, api/src/controllers/foodControllers/putFoodControllers.js, api/src/handlers/foodHandlers.js, api/src/models/Food.js, api/src/routes/foodRouter.js, api/src/routes/indexRouter.js
Se modifico el modelo de food agregandole la proiedad de category, se crearon las rutas delete y put.
No estamos extrayendo la data de la api, creamos un archivo api.js con los objetos hardcodeados. Se modifico el alter en true, para guardar la data en su base de datos, en insomnia ejecutar la siguiente url : http://localhost:3001/api.
=> Api y Rutas(delete/put)

client/src/redux/configGuide.txt, client/src/redux/foodActions.js, client/src/redux/foodSlice.js, client/src/redux/store.js, client/src/views/ReduxExperiment.jsx, comments.txt
Finished Redux configuration. 
Back-end communicated with front-end. 
Implemented foodSlice with getAllFoods and getFoodById ---> commented and to be tested once the endpoint is available. 
Implemented foodActions.js with getFoods and getFood actions ---> names to be reconsidered. 
Updated ReduxExperiment.jsx. Once Home.jsx is finnished, ReduxExperiment.jsx must be deleted.
=> Finished Redux configuration. Implemented getAllFoods action

client/src/views/Home/Home.jsx
Minor fix in Home.jsx. Added !allFods.length? inside the useEffect
=> Minor fix in Home

api/.env.example, client/src/components/Paginado/Paginado.jsx, client/src/components/Paginado/Paginado.module.css, client/src/views/Home/Home.jsx
modificando el paginado para mostrar página activa
=> modificando el paginado

client/src/views/Home/Home.jsx, client/src/views/Home/Home.module.css
=> Refactored carousel in Home.jsx

api/src/models/Food.js, client/src/views/Detail/Detail.jsx
Fixed Detail refresh with optional chainings. 
Changed diets datatypes in FoodsModel from string to array.
=> Fixed Detail refresh with optional chainings. Changed diets datatypes

api/api.js, api/src/models/Food.js
Se agregó la categoría pastas en la Api, y se modificó el modelo Food.
=> Api and Food Model updated

api/src/routes/indexRouter.js, client/src/views/Home/Home.jsx
Fixed api endpoint in indexRouter.js (back-end). Now it works properly when refreshing Home.jsx.
Uncommented Carousel in Home.jsx (front-end).
=> Fixed api endpoint. Uncommented Carousel in Home.jsx.

api/src/handlers/foodHandlers.js, client/src/redux/foodActions.js, client/src/redux/foodSlice.js, client/src/views/DashBoard/DashBoard.jsx
integrando el cloudinary al formulario, hay problemas con el controlador de post en el back, resolver
=> integrando cloudinary, hay problemas en el post del back

client/src/components/Paginado/Paginado.jsx
he reducido el paginado por si agregamos más páginas
=> paginado reducido

api/src/controllers/foodControllers/postFoodController.js, api/src/controllers/foodControllers/putFoodControllers.js, api/src/handlers/foodHandlers.js, api/src/models/Food.js
Se modifacron  los siguientes archivos : (postFoodController,putFoodController,postFoodHandler y el modelo Food)
=> Editando errores

api/src/controllers/foodControllers/FoodByNameController.js, client/src/components/Card/Card.jsx, client/src/components/CardsContainer/CardsContainer.jsx, client/src/components/CardsContainer/CardsContainer.module.css, client/src/components/SearchBar/SearchBar.jsx, client/src/views/Home/Home.jsx
Updated getAllFoodController to accept accents. Now it returns an empty array when there are no results (instead of a "No se encontraron resultados" string). 
Updated CardsContainer to conditionally render if there are no results. 
Updated handleChange in SearchBar to dispatch event.target.value instead of name from the localState. 
Made minor format changes. 
…e when there are no resu
lts
=> Fixed SearchBar. It accepts accents and sends a "no results". Other minor changes

client/src/components/SearchBar/SearchBar.jsx
Updated name of getFoodByName in SearchBar.jsx after filter by category and sorts commit.
=> Fixed getFoodByName variable name in SearchBar.jsx

client/src/components/Card/Card.jsx, client/src/components/Card/Card.module.css, client/src/components/CardsContainer/CardsContainer.module.css, client/src/index.css, client/src/views/DashBoard/DashBoard.jsx, client/src/views/DashBoard/DashBoard.module.css, client/src/views/Home/Home.jsx, client/src/views/Home/Home.module.css
=> Reestructuracion del estilado de las card.

api/src/controllers/foodControllers/deleteFoodController.js, api/src/controllers/foodControllers/putFoodController.js, api/src/handlers/foodHandlers.js, api/src/routes/foodRouter.js
Modifico la ruta putFood aplicando cloudinary (En caso de querer modifcar una imagen)
Modifico la ruta deleteFood aplicando cloudinary(E caso de que la imagen venga de cloudinary,se elimina de ahi tambien)
=> Edit put food

api/src/controllers/foodControllers/getFoodByNameController.js
Se modificó el "getFoodByNameController", ahora los datos se buscan y se filtran directamente en la base de datos.
=> getFoodByNameController modified

api/src/controllers/foodControllers/getAllFoodsController.js
Desde ahora las viandas se traerán en un orden random, generando que en cada renderización se muestren diferentes viandas en el home.
=> getAllFoodController updated

client/src/views/DashBoard/DashBoard.jsx, client/src/views/DashBoard/DashBoard.module.css
Updated margins, replaces logo for a button and other minor changes
=> Minor update styles in Dashboard

client/src/views/Detail/Detail.jsx, client/src/views/Detail/Detail.module.css
=> Styles Detail

client/src/components/Nav/Nav.jsx, client/src/views/DashBoard/DashBoard.module.css, client/src/views/DashBoard/Home.module.css, client/src/views/DashBoard/HomeDB.jsx
=> Styled Dashboard edit section (WIP)

client/src/App.jsx, client/src/redux/foodSlice.js, client/src/views/DashBoard/HomeDB.jsx
renderiza el home de dashboard, hay que arreglar el paginado
=> ya renderiza el home de bashboard

client/src/views/Detail/Detail.module.css
=> Editing detail view styles

client/src/components/Nav/Nav.module.css, client/src/components/SearchBar/SearchBar.module.css
Encuadrando en Nav Logo, input Searchbar y button dashboard.
=> Encuadre de Nav

client/src/components/Nav/Nav.jsx, client/src/index.css, client/src/views/Home/Home.jsx, client/src/views/Home/Home.module.css
Minor styles changes for first demo. 
Commented SearchBar in Nav. 
Commented Reset filters button. 
Fixed error message string when filtering by name
=> Minor styles changes for first demo

client/src/views/DashBoard/EditForm.jsx
Se modifico el componente edit.jsx para que pueda editar y borrar productos usando el backend
=> Put and delete

client/src/views/DashBoard/HomeDB.jsx
Pagination in HomeDB was not working properly. It is commented for the first demo.
=> Commented Pagination in HomeDB.jsx

api/src/handlers/foodHandlers.js
Se agrega logica para el final_price en el put_food
=> Correcion de price_final

client/src/components/filtersDietsOptions/filterDietsOptions.jsx
Se corrigio el filtro por dietas, especificamente 'Sin lactosa'
=> Filter correction

client/src/views/DashBoard/EditForm.jsx
mensajes de alerta para editar y eliminar vianda
=> mensajes de alerta en editar y eliminar implementados

api/src/controllers/userControllers/deleteUserController.js, api/src/controllers/userControllers/getAllusersController.js, api/src/controllers/userControllers/getUserByNameController.js, api/src/controllers/userControllers/postUserController.js, api/src/controllers/userControllers/putUserController.js, api/src/handlers/userHandlers.js, api/src/routes/foodRouter.js, api/src/routes/indexRouter.js, api/src/routes/userRouter.js
Endpoints for user implemented: GET, POST, PUT, DELETE. 
User model is not implemented yet. Onces it is implemented, attributes should be added to handlers and controllers where it is commented as /* add attributes from User model */ 
Tested with Postman, it works properly. 
POST
GET
GET by name
PUT
GET after PUT
DELETE
GET after delete
=> Implemented user route, handlers and controllers

api/src/db.js, api/src/models/Order.js
=> diseñando modelo order

api/src/db.js, api/src/models/Detail.js
definiendo las foreignkeys de order y detail
=> definiendo las foreignkeys de order y detail

api/src/db.js, api/src/models/Item.js
actualizando el nombre de la tabla detail a item
=> renombrando tabla detail por item

api/src/db.js, api/src/models/User.js, client/src/index.css
=> User Model Created

api/package.json, api/src/nodemailer/sendEmail.js
1- Actualizar dependencias: Nodemailer
2-Se agrego nodemailer y configuración básica a la carpeta api.
=> Models routes

client/package.json, client/src/App.jsx, client/src/LoginComponents/LoginButton/LoginButton.jsx, client/src/LoginComponents/LogoutButton/LogoutButton.jsx, client/src/clientComponents/Footer/Footer.jsx, client/src/clientComponents/Nav/Nav.jsx, client/src/clientViews/Home/Home.jsx, client/src/clientViews/Login/Login.jsx, client/src/index.css, client/src/main.jsx, comments.txt
Para ingresar al home: http://localhost:5173/home (de momento http://localhost:5173/ no redirige a Home porque Auth0 no está tomando como URL callback a ninguna URL que no sea http://localhost:5173). 
Para ingresar como cliente, ingresar directo a /home. 
Para ingresar como admin: iniciar sesión desde http://localhost:5173, por ejemplo con Gmail, y dirigirse luego manualmente a http://localhost:5173/home. 
Esto es sólo provisorio hasta que Auth0 esté configurado completamente. 
Ver video en Whatsapp.
=> Implemented Auth0. Read comment

client/src/App.jsx, client/src/LoginComponents/Login.jsx, client/src/LoginComponents/LoginButton/LoginButton.jsx, client/src/LoginComponents/LogoutButton/LogoutButton.jsx, client/src/main.jsx, comments.txt
Home rendered in root ("/") instead of in "/home". With this change, Auth0 works properly.
=> Auth0 called in root instead of in Home

client/src/redux/foodActions.js, client/src/redux/foodSlice.js
Se agrego dos actions addItemAcction y deleteItemActions y reducer action addItems y deleteItems
=> Actions - addItemAcction y deleteItemActions

client/src/clientComponents/Paginado/Paginado.jsx, client/src/clientViews/Detail/Detail.jsx
implementando boton de agregar carrito al componente detail para que cliente pueda agregar vianda incluso si está viendo el detalle de la vianda.
=> Shoppingcar

client/src/clientViews/Detail/Detail.jsx
import of useState to fix the cards detail
=> detail correction

client/src/clientViews/Detail/Detail.jsx, client/src/clientViews/ShoppingCar/ShoppingCar.jsx
corrigiendo botón de agregar al carrito en detalle
=> corrigiendo botón de agregar al carrito en detalle

client/src/App.jsx, client/src/clientViews/Detail/Detail.jsx, client/src/clientViews/MyProfile/MyProfile.jsx, client/src/redux/store.js, client/src/redux/userSlice.js
userSlice created with functions to get all users from DB and get the detail of user by name(recommended to modify the getuserbyname controller and change it to get the users data by email instead)
=> userSlice created

api/src/controllers/userControllers/getUserByNameController.js, api/src/handlers/userHandlers.js, api/src/models/User.js
Now the POST and GET user ccontrollers and handlers use the email instead of the name. 
Now the User model only requires the email (allownull:false)
=> Updated User model and users controllers and handlers

client/src/App.jsx, client/src/clientViews/MyProfile/MyProfile.jsx, client/src/redux/userSlice.js
userSlice variables name changed to better understanding of the code
=> variables name fix

api/src/controllers/userControllers/getUserByEmailController.js, api/src/handlers/userHandlers.js, api/src/models/User.js, client/src/App.jsx, client/src/clientViews/MyProfile/MyProfile.jsx
MyProfile WIP
Updated User model
=> MyProfile WIP

client/src/App.jsx, client/src/clientComponents/Nav/Nav.jsx, client/src/clientViews/MyProfile/MyProfile.jsx, client/src/redux/userSlice.js
Updated Nav. 
- It renders conditionally the button to MyProfile if isAuthenticated is true. 
- It renders the shoppingCart button.
=> Updated Nav WIP

api/package.json, api/src/app.js, api/src/handlers/shoppingCartHandlers.js, api/src/routes/indexRouter.js, api/src/routes/shoppingCartRouter.js
Se crearon rutas fundamentales. Queda pendientes las configuraciones para la conexión con el front, y las bases de datos.
=> Mercadopago Seteo Inicial

api/src/controllers/userControllers/postUserController.js, client/src/clientViews/Home/Home.jsx
Al ingresar un nuevo usuario se guarda en la base de datos el nombre y coreo.
Se modificó la lógica de "postUserController", y se agregó un useEffect con sus variables en "Home".
FALLA ACTUAL: Se están enviado dos correos de Bienvenida al loguearse por primea vez.
=> Store User Data Implemented

client/src/App.jsx, client/src/clientComponents/Nav/Nav.jsx, client/src/clientComponents/Nav/Nav.module.css
=> Implemented user icon in Nav. Deleted unnecessary query in myprofile

api/src/controllers/userControllers/postUserController.js, api/src/handlers/userHandlers.js, api/src/models/User.js, client/src/clientViews/Home/Home.jsx
Updated User model (now the PK is the id). Updated Home.jsx to call POST /user with a type: guest if the client is not authenticated
=> Automatic creation of guest user 

client/src/clientComponents/Nav/Nav.jsx, client/src/clientComponents/Nav/Nav.module.css, client/src/index.css
Styled Nav rendering depending to the authtentication but still not with different permissions.
=> Styled Nav

api/src/controllers/itemControllers/postItemController.js, api/src/handlers/itemHandlers.js, api/src/handlers/shoppingCartHandlers.js, api/src/models/Item.js, api/src/routes/indexRouter.js, api/src/routes/itemRouter.js
Se crearon las rutas, handlers y controllers básicos del modelo Item.
=> Item Routes Created

api/src/controllers/userControllers/postUserController.js, api/src/controllers/userControllers/putUserController.js, api/src/handlers/userHandlers.js, api/src/models/User.js, api/src/routes/userRouter.js, client/src/clientViews/MyProfile/MyProfile.jsx, client/src/clientViews/MyProfile/MyProfile.module.css
Comment: replaced "adress" for "address" in the whole project.
=> Added logic to Mis datos in MyProfile view. Name is already working

client/src/clientViews/Home/Home.jsx, client/src/clientViews/Home/Home.module.css
home con carrousell y tres card renderizadas debajo.
=> cambios en home renderizado de tres card

api/index.js, api/src/controllers/orderControllers/getOrdersController.js, api/src/controllers/orderControllers/postOrderController.js, api/src/handlers/orderHandlers.js, api/src/models/Order.js, client/src/clientComponents/Card/Card.jsx, client/src/clientComponents/CategoryButtons/CategoryButtons.module.css, client/src/clientComponents/ShoppingCar/Checkout.jsx, client/src/clientViews/Viandas/Viandas.jsx, client/src/clientViews/Viandas/Viandas.module.css
=> Detalles de estilado del componente viandas

api/index.js, api/src/controllers/itemControllers/deleteItemController.js, api/src/controllers/itemControllers/postItemController.js, api/src/controllers/itemControllers/updateCartTotalPrice.js, api/src/controllers/orderControllers/getOrderByUserIdController.js, api/src/controllers/orderControllers/postOrderController.js, api/src/handlers/itemHandlers.js, api/src/handlers/orderHandlers.js, api/src/handlers/shoppingCartHandlers.js, api/src/models/Order.js, api/src/routes/itemRouter.js, api/src/routes/orderRouter.js, client/src/clientComponents/Card/Card.jsx, client/src/clientViews/Detail/Detail.jsx, client/src/clientViews/Home/Home.jsx, client/src/clientViews/ShoppingCar/ShoppingCar.jsx, client/src/main.jsx, client/src/redux/foodActions.js
Configuración Básica del server de Mercadopago.
Queda pendiente editar Orders e Items, y guardar la info que devuelve mercadopago.
Se modificó la credencial de mercadopago del front, para poder hacer las pruebas correspondientes.
=> Mp server config

api/src/handlers/shoppingCartHandlers.js
Se corrigió error de lógica en "createPreferenceHandler".
=> Back Front

api/api.js, client/src/clientViews/Home/Home.jsx, client/src/clientViews/Home/Home.module.css
=> Added dynamic render of foods with high score in Home.jsx. Styled  button

api/src/handlers/foodHandlers.js, client/src/adminComponents/ListProductsItam/ListProductsItem.jsx, client/src/clientComponents/CardsContainer/CardsContainer.jsx
Se agrego funcionalidad al select de la listas de viandas en el panel admin.
se modifico la renderizacion de cardsContainer para que solo renderize las habilitadas.
=> Habilitar o deshabilitar

api/src/controllers/foodControllers/getAdminFoodsController.js, api/src/controllers/foodControllers/getAllFoodsController.js, api/src/controllers/foodControllers/getFoodByNameController.js, api/src/handlers/foodHandlers.js, api/src/routes/foodRouter.js, client/src/adminComponents/Products/Products.jsx, client/src/adminViews/AdminPanel/AdminPanel.jsx, client/src/clientComponents/CardsContainer/CardsContainer.jsx, client/src/redux/foodActions.js, client/src/redux/foodSlice.js
Se cambio la logica para habilitar y deshabilitar productos por problemas con la renderizacion.
=> Admin errors

client/src/clientComponents/Card/Card.jsx, client/src/clientViews/Detail/Detail.jsx
Se corrigieron cambios eliminados en el merge #203
=> Errores arreglados

client/src/clientComponents/Card/Card.jsx
cambio de alert de windows por alert de sweet en card
=> cambio alert en card

client/src/clientComponents/Nav/Nav.jsx, client/src/clientComponents/Nav/Nav.module.css
=> Avance de Navbar vista mobil

api/src/controllers/orderControllers/putOrderController.js, api/src/handlers/orderHandlers.js, client/src/clientViews/PaymentStatus/PaymentStatus.jsx
Se modificó el formato que envía el front para el atributo DATE del modelo Order en el back.
=> Order Date DB Fixed

client/src/LoginComponents/LoginButton/LoginButton.css, client/src/LoginComponents/LoginButton/LoginButton.jsx, client/src/clientComponents/Card/Card.jsx, client/src/clientComponents/Card/Card.module.css, client/src/clientComponents/Nav/Nav.module.css, client/src/clientViews/Detail/Detail.module.css, client/src/clientViews/Home/Home.module.css
Modificación del hover y acomodar la nav en botón inicio. Acomodar las imagenes de las card
=> modificacion de nav y cards

api/src/controllers/orderControllers/getOrdersController.js, api/src/handlers/orderHandlers.js
Se modifico ruta getOrders para el admin
=> Modificando ruta orders para admin

api/src/controllers/reviewControllers/getAllReviewsController.js, api/src/controllers/reviewControllers/getReviewByIdController.js, api/src/controllers/reviewControllers/postReviewController.js, api/src/controllers/reviewControllers/putReviewController.js, api/src/handlers/reviewHandlers.js, api/src/models/Review.js, api/src/routes/indexRouter.js, api/src/routes/reviewRouter.js
Se crearon las rutas post, put(que todavia solo devuelve string ya que podria ser innecesaria) y get a "/review".
Tambien se modifico el modelo de Review. agregando dos propiedades: comment y rating.
=> Rutas listas

api/package.json, api/src/controllers/orderControllers/postOrderController.js, client/src/clientComponents/ShoppingCar/Checkout.jsx, client/src/clientViews/Home/Home.jsx, client/src/clientViews/ShoppingCar/ShoppingCar.jsx, client/src/redux/shopingCartSlice.js
Primeros avanzes.
Ahora el checkout renderiza el estado global de la order, el cual se carga en el useEffect del home.
Faltaria adaptar las funcionalidades para el agregado de items y la modificacion de cantidad.
=> Refactorizando el shopingCart

client/src/adminComponents/SideBar/SideBar.jsx, client/src/adminViews/AdminPanel/AdminPanel.jsx, client/src/redux/adminSlice.js
Se cambio de estado a local a global la opcion seleccionada del sidebar
=> Change local state to global state

api/package.json, api/src/handlers/shoppingCartHandlers.js, api/src/routes/mercadopagoRouter.js, client/src/clientViews/ShoppingCar/ShoppingCar.jsx
Se recibe a una ruta del back los datos del pago realizado, falta trabajar esa data para guardarla en la DB.
Se cambiaron los tokens del usuario "Vendedor".
=> PaymentData Received

api/src/controllers/mercadopagoControllers/createPreferenceController.js, api/src/controllers/mercadopagoControllers/paymentDataController.js, api/src/controllers/orderControllers/getOrderByUserIdController.js, api/src/controllers/orderControllers/postOrderController.js, api/src/handlers/shoppingCartHandlers.js, api/src/routes/mercadopagoRouter.js, client/src/clientViews/ShoppingCar/ShoppingCar.jsx
Se modularizó los handlers y controllers de la ruta "mercadopago".
=> Mercadopago Handlers Moulularized

api/src/controllers/mercadopagoControllers/createPreferenceController.js, api/src/controllers/mercadopagoControllers/paymentDataController.js, api/src/controllers/orderControllers/getOrderByUserIdController.js, api/src/controllers/orderControllers/getPendingOrderByUserEmailController.js, api/src/handlers/shoppingCartHandlers.js, api/src/routes/mercadopagoRouter.js, client/src/clientViews/ShoppingCar/ShoppingCar.jsx
Se agregó el ID de la orden a los datos del pago que trae el endpoint de mercadopago.
=> OrderId Related With Payment Status

api/package.json, api/src/controllers/mercadopagoControllers/paymentDataController.js, api/src/controllers/orderControllers/putOrderController.js, api/src/handlers/orderHandlers.js, api/src/models/Order.js, client/src/clientViews/PaymentStatus/PaymentStatus.jsx
Los datos de la operación realizado en mercadopago se guardan en la "Order" de la DB.
=> Payment Data Update to DB

client/src/clientComponents/Card/Card.jsx, client/src/clientComponents/CategoryButtons/CategoryButtons.jsx, client/src/clientComponents/CategoryButtons/CategoryButtons.module.css, client/src/redux/foodActions.js, client/src/redux/foodSlice.js
The reset button "Todas" doesn't work when combining it with diets filter.
=> Restyled filters. Added a reset button

client/index.html, client/src/clientComponents/Card/Card.jsx, client/src/clientComponents/FilterDietsOptions/FilterDietsOptions.jsx, client/src/clientViews/Viandas/Viandas.jsx
There are no more errors neither warnings on browser's console.
=> Deleted Footer.module.css from html. Replaced cassName for className

client/src/clientComponents/Paginado/Paginado.jsx, client/src/clientComponents/Paginado/Paginado.module.css
=> Added previos and next buttons to Pagination. Rendered all pages

api/src/controllers/mercadopagoControllers/createPreferenceController.js
Se modificaron las rutas de mercadopago, para que funcionen en el deploy.
=> Mercadopago URLS Modified for Deploy

client/src/clientComponents/Card/Card.jsx, client/src/clientComponents/Card/Card.module.css
=> Styled Card with the new elements. Added a like button without functionality

client/src/clientComponents/Card/Card.jsx, client/src/clientComponents/ShoppingCar/Checkout.jsx, client/src/clientComponents/ShoppingCar/Payment.jsx, client/src/clientViews/Home/Home.jsx
debugueando eliminar del carrito II
=> debugueando eliminar del carrito II

api/index.js, api/package.json, api/src/app.js, api/src/controllers/favoriteControllers/getFavoritesByEmailController.js, api/src/controllers/favoriteControllers/postFavoriteController.js, api/src/handlers/favoriteHandlers.js, api/src/routes/favoriteRouter.js, api/src/routes/indexRouter.js, client/vercel.json
Implemented POST and GET. 
Added vercel.json. 
Set force:true in index.js and replaced node for nodemon in package.json (back-end).
=> Implemented favorite route (WIP)

api/src/controllers/favoriteControllers/postFavoriteController.js, client/src/clientComponents/Card/Card.jsx, client/src/clientComponents/Card/Card.module.css, client/src/clientComponents/LikeButton/LikeButton.jsx, client/src/clientComponents/LikeButton/LikeButton.module.css, client/src/clientComponents/Paginado/Paginado.jsx, client/src/clientViews/Home/Home.jsx, client/src/index.css, client/src/redux/userSlice.js, comments.txt
Next step: communicate with POST /favorite . After that, create a DELETE /favorite endpoint.
=> Front-end communicated with GET /favorite

api/src/controllers/orderControllers/getBestSellersController.js, api/src/handlers/orderHandlers.js, client/src/adminComponents/DashBoard/DashBoard.jsx, client/src/adminComponents/DashBoard/DashBoard.module.css, client/src/adminComponents/DashBoard/PieChart.jsx, client/src/adminComponents/DashBoard/PieChart.module.css, client/src/redux/adminSlice.js
Se agrego funcionalidad en el pieChart del dashboard para elegir la cantidad de productos a mostrar.
Las opciones actuales pueden ser modificadas.
=> opcion de cantidad de productos a mostrar en el pieChart

api/src/controllers/orderControllers/getOrdersController.js, api/src/handlers/orderHandlers.js, api/src/routes/orderRouter.js
Cambio de body a params ordenes de usuario
=> Renderizar status order

client/src/clientViews/UserOrderDetail/UserOrderDetail.jsx, client/src/clientViews/UserOrderDetail/UserOrderDetail.module.css
=> Estilos orders

api/src/controllers/itemControllers/deleteItemController.js, client/src/clientComponents/ShoppingCar/Checkout.jsx, client/src/redux/shopingCartSlice.js
debugueando el delete del cart
=> debugueando el delete del cart

api/src/controllers/reviewControllers/postReviewController.js
Se agrego funcionalidad a la ruta que crea reviews, para que calcule el total_score de una vianda
=> Calcular total_score

client/src/clientViews/Home/Home.jsx, client/src/clientViews/Home/Home.module.css, client/src/index.css
=> Added greeting in Home.jsx

client/src/adminViews/CreateFood/CreateFood.jsx, client/src/adminViews/CreateFood/CreateFood.module.css, client/src/adminViews/EditFood/EditFood.jsx, client/src/adminViews/EditFood/EditFood.module.css
Next step: restyle components.
=> Added SideBar to CreateFood.jsx and EditFood.jsx

api/api.js, api/src/controllers/foodControllers/putFoodController.js, api/src/handlers/foodHandlers.js
=> Added Math.ceil to final_price in putFoodHandler and postFoodHandler

client/src/clientComponents/Card/Card.jsx, client/src/clientComponents/Card/Card.module.css, client/src/clientComponents/CardsContainer/CardsContainer.jsx, client/src/clientViews/Viandas/Viandas.jsx
=> Added a star in products with score greater than 4

api/package.json, client/src/adminComponents/ListUsers/ListUsers.jsx, client/src/adminComponents/ListUsers/ListUsers.module.css, client/src/adminComponents/Users/Users.jsx, client/src/adminComponents/Users/Users.module.css, client/src/clientViews/Home/Home.jsx, client/src/redux/adminSlice.js, client/src/redux/userSlice.js
Primer maquetado de la seccion usuarios en el panel admin.
Falta agregar funcionalidad.
=> Primer maquetado

api/index.js, client/src/App.jsx, client/src/clientComponents/SidebarUser/SidebarUser.jsx, client/src/clientViews/MyFavorites/MyFavorites.jsx, client/src/clientViews/MyFavorites/MyFavorites.module.css, client/src/clientViews/UserOrder/UserOrder.jsx
Created component Favorites.jsx. Created route "/micuenta/misfavoritos". Added link to UserSideBar.
=> Added Favorites to UserPanel

api/src/controllers/userControllers/putUserController.js, api/src/handlers/userHandlers.js, api/src/models/User.js, client/src/clientViews/MyProfile/MyProfile.jsx, client/src/clientViews/MyProfile/MyProfile.module.css, client/src/redux/userSlice.js
The putController was modified according to edit only the address. To edit other properties as type, the controller should be modified
=> Added functionality to MyProfile.jsx. It allows the user to change the address

client/src/adminComponents/ListProductsItam/ListProductsItem.jsx, client/src/adminComponents/Products/Products.jsx, client/src/adminComponents/SearchBarProducts/SearchBarProducts.jsx, client/src/adminViews/CreateFood/CreateFood.jsx, client/src/adminViews/EditFood/EditFood.jsx, client/src/redux/adminSlice.js
Se agrego searchbar a la seccion de viandas en panel admin.
=> Add searchbar admin
